/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado.juego;

import javax.swing.DefaultListModel;

/**
 *
 * @author Yo
 */

public class ConfigPalabras extends javax.swing.JFrame {

    /**
     * Creates new form ConfigPalabras
     */
    Diccionario dicc;
    Menu menu;
    DefaultListModel<String> model;
    boolean[] areYouSure;
    
    public ConfigPalabras(Menu menu) {
        this.menu=menu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDificultad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dificultadFacil = new javax.swing.JRadioButton();
        dificultadMedio = new javax.swing.JRadioButton();
        dificultadDificil = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Borrar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPalabras = new javax.swing.JList<>();
        cargarLista = new javax.swing.JButton();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        grupoDificultad.add(dificultadFacil);
        dificultadFacil.setText("Facil");

        grupoDificultad.add(dificultadMedio);
        dificultadMedio.setSelected(true);
        dificultadMedio.setText("Normal");

        grupoDificultad.add(dificultadDificil);
        dificultadDificil.setText("Dificil");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Seleccione la dificultad de las palabras que desee administrar y presione \"Cargar lista\"");
        jScrollPane1.setViewportView(jTextArea1);

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaPalabras);

        cargarLista.setText("Cargar lista seleccionada");
        cargarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarListaActionPerformed(evt);
            }
        });

        guardar.setText("Guardar cambios");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dificultadDificil)
                            .addComponent(dificultadMedio)
                            .addComponent(cargarLista)
                            .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Borrar)
                                .addGap(75, 75, 75)
                                .addComponent(Modificar)
                                .addGap(57, 57, 57)
                                .addComponent(Agregar)
                                .addGap(49, 49, 49))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dificultadFacil)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(dificultadFacil)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dificultadMedio)
                        .addGap(18, 18, 18)
                        .addComponent(dificultadDificil)
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Borrar)
                                    .addComponent(Modificar)
                                    .addComponent(Agregar)
                                    .addComponent(guardar)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cargarLista)
                                .addGap(93, 93, 93))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarListaActionPerformed
        // TODO add your handling code here:
        this.model=new DefaultListModel<>();
        if(dificultadFacil.isSelected()==true)
       {
           this.dicc=Diccionario.deserializarPalabras("Facil");
  
       }else if(dificultadMedio.isSelected()==true)
       {
          this.dicc=Diccionario.deserializarPalabras("Normal");
       }
       else
       {
          this.dicc=Diccionario.deserializarPalabras("Dificil");
       }
        
        if(this.dicc!=null){
            
            
            for (Palabra Palabra : this.dicc.Palabras) {
                    this.model.addElement(Palabra.palabra);
            } 
            this.listaPalabras.setModel(model);
            this.listaPalabras.setVisible(true);
            
            
        }
        
        
    }//GEN-LAST:event_cargarListaActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        
        
        this.dicc.Palabras.remove(this.listaPalabras.getSelectedIndex());
        for (Palabra Palabra1 : this.dicc.Palabras) {
            System.out.println(Palabra1.palabra);
        }
        this.model.remove(this.listaPalabras.getSelectedIndex());
    }//GEN-LAST:event_BorrarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        System.out.println(this.dicc.Palabras.get(this.listaPalabras.getSelectedIndex()).palabra);
        ModificarPalabra ventana=new ModificarPalabra(this , true, this.dicc.Palabras.get(this.listaPalabras.getSelectedIndex()));
        ventana.setVisible(true);
      /*  */
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
       
        ModificarPalabra ventana=new ModificarPalabra(this , true, this.dicc);
       
        ventana.setVisible(true);
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        if(this.dicc!=null){
            
            this.model.removeAllElements();
          
            for (Palabra Palabra : this.dicc.Palabras) {
                    this.model.addElement(Palabra.palabra);
            } 
            
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    
        Seguro x;
        if(this.dicc!=null){
            if(dificultadFacil.isSelected()==true){
                x=new Seguro(this,true,dicc,"Facil");
                x.setVisible(true);
  
            }else if(dificultadMedio.isSelected()==true){
                x=new Seguro(this,true,dicc,"Normal");
                x.setVisible(true);
             }
            else{
                x=new Seguro(this,true,dicc,"Dificil");
                x.setVisible(true);
             }
            
       }
            
    }//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton cargarLista;
    private javax.swing.JRadioButton dificultadDificil;
    private javax.swing.JRadioButton dificultadFacil;
    private javax.swing.JRadioButton dificultadMedio;
    private javax.swing.ButtonGroup grupoDificultad;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> listaPalabras;
    // End of variables declaration//GEN-END:variables
}
